#!/usr/bin/python3

import sys
import os
import re
import shlex
import enum
import operator
import copy
import pprint
import subprocess
import datetime

# shortenspice
###############################################################################

def shortenSpice(spice, out):
	ckts = dict()
	ids = dict()
	with open(spice, 'r') as fptr:
		with open(out, 'w') as optr:
			for line in fptr:
				line = line.split()
				if line and line[0] == '.subckt':
					ms = re.finditer(r'[a-zA-Z]', line[1])
					if ms:
						m = None
						for m in ms:
							pass
						idx = m.span()[-1]
						if idx < len(line[1]):
							name = line[1][0:idx]
							if name in ids:
								ids[name] += 1
							else:
								ids[name] = 0
							name += '_' + str(ids[name])
							ckts[line[1]] = name
							line[1] = name
				elif line and line[0].startswith("x"):
					i = 0
					while i < len(line) and '=' in line[-1-i]:
						i += 1
					if i < len(line):
						if line[-1-i] in ckts:
							line[-1-i] = ckts[line[-1-i]]
				print(' '.join(line), file=optr)

# sim2chan
###############################################################################

def buildChan(sim, neutral=False, tohex=False):
	values = {}
	errors = {}
	
	length = 0
	skip = False
	cleanup = re.compile(r'\r[^\r]*\r')
	with open(sim, "r") as fptr:
		for l, line in enumerate(fptr):
			if "$finish" in line:
				break

			if l == 0 and "Chronologic VCS simulator" in line:
				skip = True

			if skip and "Maximum DC iterations" in line:
				skip = False
			elif not skip and "DC iteration" not in line and "DC initialization" not in line and "End of operating" not in line and "Memory usage" not in line:
				line = cleanup.sub('', line)
				idx = max([len(v) for v in values.values()] or [0])
				if len(line.strip()) > 0 and line[0] != '\t' and line[0] != '>':
					if line[0:5] == "ERROR" or line[0:7] == "WARNING":
						if idx not in errors:
							errors[idx] = ""
						errors[idx] += line
					else:
						value = [cell.strip(" \t\n{}()") for cell in line.split(': ')]
						if len(value) == 2 and (neutral or value[1] != "neutral"):
							if value[0] not in values:
								values[value[0]] = []

							if len(values[value[0]]) < length-1:
								values[value[0]].extend([":"]*(length-len(values[value[0]])-1))

							if tohex and value[1][0] in "0123456789":
								values[value[0]].append("%X" % int(value[1]))
							else:
								values[value[0]].append(value[1])
							
							if len(values[value[0]]) > length:
								length = len(values[value[0]])

	max_len = 0
	for key in values.keys():
		if len(values[key]) > max_len:
			max_len = len(values[key])

	ks = values.keys()
	keys = []
	other = []
	for k in ks:
		if '[' in k:
			idx = k[k.index('['):]
			k = k[0:k.index('[')]
			idx = [int(i) if ':' not in i else i for i in idx[1:-1].split('][')]
			keys.append((k, idx))
		else:
			other.append(k)

	keys = other + [k[0] + '[' + ']['.join([str(x) for x in k[1]]) + ']' for k in sorted(keys)]

	prefix = sim[0:-4]
	chan = prefix + '.chan'
	with open(chan, "w") as fptr:
		print('\t'.join(keys), file=fptr)
		for i in range(0, max_len):
			if i in errors:
				print(errors[i], file=fptr)
			print('\t'.join([values[key][i] if i < len(values[key]) else '' for key in keys]), file=fptr)

		for err in [e for i,e in errors.items() if i >= max_len]:
			print(err, file=fptr)
	return chan

# sim2vcd
###############################################################################

def bundle2int(bun):
	value = -1
	width = (len(bun)-1).bit_length()
	for i, c in enumerate(bun):
		if c == '1' and value == -1:
			value = i
		elif c == '1' and value >= 0:
			value = -2
	if value == -2:
		return 'x'*width # illegal
	elif value == -1:
		return '-'*width # neutral
	else:
		result = str(bin(value))[2:]
		result = '0'*(width-len(result)) + result
		return result

def vec2int(vec, sz):
	result = ""
	for i in range(0, len(vec), sz):
		result = bundle2int(vec[i:i+sz]) + result
	return result

def uniq(lst):
	used = set()
	return [(t,n) for t,n in lst if t not in used and (used.add(t) or True)]

def buildVCD(sim, normalize=False):
	signals = {}
	curid = ""
	lasttime = -1
	markers = []

	prefix = sim[0:-4]
	vcd = prefix + '.vcd'
	gtkw = prefix + '.gtkw'
	with open(sim, 'r') as fptr:
		with open(vcd, 'w') as vptr:
			# Header
			print("$date", file=vptr)
			print(datetime.datetime.now().strftime("%Y-%m-%d"), file=vptr)
			print("$end", file=vptr)
			print("$timescale 1ps $end", file=vptr)

			for line in fptr:
				line = line.strip()
				if len(line) > 0 and line[0].isdigit():
					line = re.split('[ \t]+', line)
					curtime = int(line[0])
					signal = line[1].replace(".", "_").replace("[", "").replace("]", "")
					if signal not in signals:
						signals[signal] = [signal, 1]

					while True:
						value = line[-1]
						vec = line[-1].split('=')
						if vec[-1][0] == '{':
							vecname = vec[-2].replace(".", "_").replace(":", "_").replace("[", "").replace("]", "")
							vecvalue = vec2int(vec[-1][1:-1], 2)
							if vecname not in signals:
								signals[vecname] = [vecname, len(vecvalue)]
							del line[-1]
						if vec[-1][0] == '(':
							vecname = vec[-2].replace(".", "_").replace(":", "_").replace("[", "").replace("]", "")
							vecvalue = vec2int(vec[-1][1:-1], len(vec[-1])-2)
							if vecname not in signals:
								signals[vecname] = [vecname, len(vecvalue)]
							del line[-1]
						else:
							vecname = ""
							vecvalue = ""
							break
			fptr.seek(0)

			name = [33,33,33]
			for key in reversed(sorted(signals.keys(), key=len)):
				signals[key][0] = chr(name[0]) + chr(name[1]) + chr(name[2])
				name[2] += 1
				if name[2] > 126:
					name[1] += 1
					name[2] = 33
				if name[1] > 126:
					name[0] += 1
					name[1] = 33

				print("$var wire " + str(signals[key][1]) + " " + signals[key][0] + " " + key + " " + "$end", file=vptr)

			print("$enddefinitions $end", file=vptr)
			
			# Initial Values
			print("$dumpvars", file=vptr)
			for key, value in signals.items():
				if value[1] == 1:
					print("x" + value[0], file=vptr)
				else:
					print("b" + "x"*value[1] + " " + value[0], file=vptr)
			# print X
			print("$end", file=vptr)

			# Value Change Section
			printtime = 0
			lastprinttime = 0
			for line in fptr:
				line = line.strip()
				if len(line) > 0:
					if line.startswith("WARNING"):
						if normalize:
							markers.append((lastprinttime, "WARNING"))
						else:
							markers.append((lasttime, "WARNING"))
					elif line.startswith("ERROR"):
						if normalize:
							markers.append((lastprinttime, "ERROR"))
						else:
							markers.append((lasttime, "ERROR"))
					elif line[0].isdigit():
						line = re.split('[ \t]+', line)
						curtime = int(line[0])
						signal = line[1].replace(".", "_").replace("[", "").replace("]", "")
						value = line[3]
						if curtime != lasttime:
							if normalize:
								print("#" + str(printtime), file=vptr)
							else:
								print("#" + str(curtime), file=vptr)
							lastprinttime = printtime
							printtime += 10
							lasttime = curtime

						print(value + signals[signal][0], file=vptr)

						while True:
							vec = line[-1].split('=')
							if vec[-1][0] == '{':
								vecname = vec[-2].replace(".", "_").replace(":", "_").replace("[", "").replace("]", "")
								vecvalue = vec2int(vec[-1][1:-1], 2)
								del line[-1]
							elif vec[-1][0] == '(':
								vecname = vec[-2].replace(".", "_").replace(":", "_").replace("[", "").replace("]", "")
								vecvalue = vec2int(vec[-1][1:-1], len(vec[-1])-2)
								del line[-1]
							else:
								vecname = ""
								vecvalue = ""
								break
							
							if vecname and vecname in signals:
								if signals[vecname][1] == 1:
									print(vecvalue + signals[vecname][0], file=vptr)
								else:
									print("b" + vecvalue + " " + signals[vecname][0], file=vptr)
	
		with open(gtkw, 'w') as gptr:
			print("[dumpfile] \"" + os.getcwd() + "/" + vcd + "\"", file=gptr)
			print("[savefile] \"" + os.getcwd() + "/" + gtkw + "\"", file=gptr)
			markers = uniq(markers)
			print("*1.0 0 " + " ".join([str(t) for t, n in markers]), file=gptr)
			for l, (t, n) in zip("ABCDEFGHIJKLMNOPQRSTUVWXYZ", markers):
				print("[markername] " + l + n, file=gptr)

	return vcd

# Helper Functions
###############################################################################

def projectRoot():
	path = os.getcwd()
	while path and path != "/" and not os.path.exists(path + "/go.mod"):
		path = os.path.dirname(path)
	return path

def relativeCwd(root):
	return os.path.relpath(os.getcwd(), start=root)

# Expression Parser
###############################################################################

class Token:
	def __init__(self, token_type, value=None):
		self.token_type = token_type
		self.value = value
		self.children = []

def lexExp(s):
	tokens = []
	curr = None
	for c in s:
		if c in ['+', '-', '*', '/', '(', ')']:
			if curr != None:
				tokens.append(curr)
				curr = None

			tokens.append(Token(c, value=c))
		elif (curr == None or curr.token_type != 'v') and re.match(r'\d', c):
			if curr != None and curr.token_type != 'n':
				tokens.append(curr)
				curr = None

			if curr != None:
				curr.value += c
			else:
				curr = Token('n', value=c)
		elif ((curr == None or curr.token_type != 'v') and re.match(r'[A-Za-z_]', c)) or (curr != None and curr.token_type == 'v' and re.match(r'[A-Za-z0-9_]', c)):
			if curr != None and curr.token_type != 'v':
				tokens.append(curr)
				curr = None

			if curr != None:
				curr.value += c
			else:
				curr = Token('v', value=c)
		else:
			raise Exception('Invalid token: {}'.format(c))
	if curr != None:
		tokens.append(curr)
	tokens.append(Token('e'))
	return tokens

def expectToken(tokens, token):
	if tokens[0].token_type == token:
		return tokens.pop(0)
	else:
		raise Exception('Invalid syntax on token {}'.format(tokens[0].token_type))

def parseExpAddSub(tokens):
	left_node = parseExpMulDiv(tokens)

	while tokens[0].token_type in ['+', '-']:
		node = tokens.pop(0)
		node.children.append(left_node)
		node.children.append(parseExpMulDiv(tokens))
		left_node = node

	return left_node

def parseExpMulDiv(tokens):
	left_node = parseExpParens(tokens)

	while tokens[0].token_type in ['*', '/']:
		node = tokens.pop(0)
		node.children.append(left_node)
		node.children.append(parseExpParens(tokens))
		left_node = node

	return left_node

def parseExpParens(tokens):
	if tokens[0].token_type == 'n':
		return tokens.pop(0)
	elif tokens[0].token_type == 'v':
		return tokens.pop(0)

	expectToken(tokens, '(')
	expression = parseExpAddSub(tokens)
	expectToken(tokens, ')')

	return expression

def parseExp(inputstring):
	tokens = lexExp(inputstring)
	ast = parseExpAddSub(tokens)
	expectToken(tokens, 'e')
	return ast

operations = {
	'+': operator.add,
	'-': operator.sub,
	'*': operator.mul,
	'/': operator.truediv
}

def evalExp(expr, params):
	node = expr
	if isinstance(expr, str):
		node = parseExp(expr)
	if node.token_type == 'n':
		return int(node.value)
	elif node.token_type == 'v':
		if node.value in params:
			return int(params[node.value])
	left_result = evalExp(node.children[0], params)
	right_result = evalExp(node.children[1], params)
	operation = operations[node.token_type]
	return operation(left_result, right_result)

# Act Parser
###############################################################################

class ActType:
	def __init__(self, name, params):
		self.name = name     # str
		self.params = params # list(int)

	def __str__(self):
		if self.params:
			return self.name + "<" + ",".join([str(param) for param in self.params]) + ">"
		else:
			return self.name

	def flatten(self, params):
		for i, param in enumerate(self.params):
			self.params[i] = str(evalExp(param, params))

	def isBundledData(self):
		return self.name.startswith("bus2_") or self.name.startswith("bus_")


class ActArg:
	def __init__(self, name, size, vtype):
		self.name = name   # str
		self.size = size   # list(int)
		self.vtype = vtype # ActType

	def flatten(self, params):
		self.vtype.flatten(params)
		for i, size in enumerate(self.size):
			self.size[i] = str(evalExp(size, params))

	def signalName(self):
		result = self.name
		if self.vtype.isBundledData():
			result += ".c"
		return result

	def signalRails(self):
		if self.vtype.isBundledData():
			return self.vtype.params[1]
		elif len(self.vtype.params) > 0:
			return self.vtype.params[0]
		else:
			return 0

	def index(self, i):
		return ActArg(self.name + "[" + str(i) + "]", self.size[1:], self.vtype)

	def instName(self):
		return self.name + "".join(["[" + s + "]" for s in self.size])

	def inst(self):
		return str(self.vtype) + " " + self.instName()

	def count(self):
		if len(self.size) > 0:
			return self.size[-1]
		return 0

	def sinkType(self):
		result = copy.deepcopy(self.vtype)
		if result.name.startswith("bus2_"):
			result.name = result.name[5:]
			result.params = [result.params[1]]
		elif result.name.startswith("bus_"):
			result.name = result.name[4:]
			result.params = [result.params[1]]
		result.params.append(6)
		return result

	def sink(self):
		lines = []
		if "[" not in self.name:
			lines.append("sink_{vtype} sink_{name};".format(
				vtype = str(self.sinkType()),
				name = self.instName(),
			))
		if len(self.size) > 0:
			for i in range(0, int(self.size[0])):
				lines += self.index(i).sink()
		else:
			lines.append("sink_{name}(g, {signals});".format(
				name = self.name,
				signals = self.signalName(),
			))
		return "\n".join(lines)

	def emitBundle(self):
		if len(self.size) > 0:
			lines = []
			for i in range(0, int(self.size[0])):
				lines += self.index(i).emitBundle()
			return lines
		
		if self.vtype.name.endswith("e1of") or self.vtype.name.endswith("eMofN") or self.vtype.name.endswith("a1of") or self.vtype.name.endswith("aMofN") or self.vtype.name.endswith("c1of") or self.vtype.name.endswith("cMofN"):
			return ["bundle dut.{name}.d[0:{rails}]".format(
				name  = self.signalName(),
				rails = self.signalRails(),
			)]

		return []

	def emit(self, chp):
		if len(self.size) > 0:
			lines = []
			for i in range(0, int(self.size[0])):
				lines += self.index(i).emit(chp.index(i))
			return lines

		if self.vtype.name in ["bool", "pair"]:
			if chp.name in ["false", "true"]:
				value = (1 if chp.name == "true" else 0)
				if self.vtype.name == "bool":
					return ["set dut.{name} {value}".format(name=self.name, value=value)]
				else:
					return [
						"set dut.{name}.d[1] {value}".format(name=self.name, value=value),
						"set dut.{name}.d[0] {value}".format(name=self.name, value=1-value)
					]
			elif chp.clk and chp.name:
				return prsimEmitBus(self.name, chp.clk, self.count(), chp.posedge, self.vtype.name == "pair", chp.name, chp.vdir)
			return []

		protocol = ""
		ack = chp.clk
		posedge = chp.posedge
		clk = chp.clk
		if self.vtype.name.endswith("e1of") or self.vtype.name.endswith("eMofN") or self.vtype.name.endswith("ePxMofN"):
			protocol = "e"
			ack = ""
			clk = self.signalName()+".e"
			posedge = True
		elif self.vtype.name.endswith("a1of") or self.vtype.name.endswith("aMofN") or self.vtype.name.endswith("aPxMofN"):
			protocol = "a"
			ack = ""
			clk = self.signalname()+".a"
			posedge = False
		elif self.vtype.name.endswith("c1of") or self.vtype.name.endswith("cMofN") or self.vtype.name.endswith("cPxMofN"):
			protocol = ("a" if chp.ack else "e")

		lines = []
		if protocol:
			req = self.signalName() + ".d[0:{rails}]".format(rails=self.signalRails())
			data = chp.name + (".C" if self.vtype.isBundledData() else "")
			lines += prsimEmitChan(self.signalName(), protocol, req, ack, data, chp.vdir)

		if self.vtype.name.startswith("bus2_") or self.vtype.name.startswith("bus_"):
			data = chp.name + (".D" if self.vtype.isBundledData() else "")
			lines += prsimEmitBus(self.name, clk, self.vtype.params[0], posedge, self.vtype.name.startswith("bus2_"), data, chp.vdir)
		return lines

class ActProcess:
	def __init__(self, path, tmpl, args):
		self.path = path
		self.tmpl = tmpl
		self.args = args

	def flatten(self, values):
		params = {param.name: value for param, value in zip(self.tmpl, values)}

		result = copy.deepcopy(self)
		for arg in result.args:
			arg.flatten(params)
		return result

	def argdef(self):
		return "; ".join([arg.inst() for arg in self.args])

	def arglist(self):
		return ",".join([arg.name for arg in self.args])	

class ActInstance:
	def __init__(self, name, tmpl, args):
		self.name = name
		self.tmpl = tmpl
		self.args = args

	def test(self):
		return self.name.replace('::', '_') + '_' + '_'.join(self.tmpl)

	def typestr(self):
		return self.name + "<" + ",".join(self.tmpl) + ">"

def parseArgs(line):
	result = []
	for arg in line.split(","):
		result.append(arg.strip())
	return result

def parseActType(line):
	o = line.find("<")
	c = line.rfind(">")
	if o != -1 and c != -1:
		return ActType(line[0:o], parseArgs(line[o+1:c]))
	else:
		return ActType(line, [])

def parseArray(line):
	name = ""
	size = []

	terms = line.strip().split("[")
	name = terms[0]
	size = [term[0:-1] for term in terms[1:]]
	return (name, size)
	
def parseActArgs(line):
	args = []
	for elem in line.split(";"):
		m = re.match(r'([a-zA-Z_][a-zA-Z_0-9]*(?:<[^>]*>)?) *(.*)', elem.strip())
		if m is not None:
			argtype = parseActType(m.group(1).strip())
			for arg in m.group(2).split(","):
				name, argsize = parseArray(arg)
				args.append(ActArg(name, argsize, argtype))
	return args

def parseActProcess():
	processes = {}
	for line in os.popen("find * -name '*.act' | grep -v \"test/\""):
		path = line.strip()
		with open(path, "r") as fptr:
			for m in re.findall(r'(?:template\s*<([^>]*)>)?\s*(?:export\s*)?defproc\s*([A-Za-z_][A-Za-z0-9_]*)\(([^\)]*)\)', fptr.read()):
				if m[1] != '':
					tmpl = None
					if m[0] != '':
						tmpl = parseActArgs(m[0])
					name = m[1]
					args = parseActArgs(m[2])
					processes[name] = ActProcess(path, tmpl, args)
	return processes

# Chp Parser
###############################################################################

class ChpStruct:
	def __init__(self, desc):
		desc = desc.strip()
		self.name = ""
		self.dtype = ""
		self.members = []
		if len(desc) == 0:
			return

		structStart = desc.index('{') if '{' in desc else len(desc)
		nameStart = desc.index(':') if ':' in desc else len(desc)
		if nameStart < structStart and nameStart < len(desc):
			self.name = desc[0:nameStart]
			desc = desc[nameStart+1:]
			structStart -= nameStart+1
		if structStart < len(desc):
			self.members = [ChpStruct(arg) for arg in desc[structStart+1:-1].split(" ")]

		self.dtype = desc

	def __str__(self):
		return (self.name + ":" if self.name else "") + (self.dtype if self.dtype else "")

	# return list of indexes into members for a particular member name
	def addr(self, name):
		search = name
		sub = ""
		if '.' in search:
			idx = search.index('.')
			sub = search[idx+1:]
			search = search[0:idx]

		for i, member in enumerate(self.members):
			if member.name == search:
				return [i] + member.addr(sub)

		return []

	# return a particular member given a list of indexes
	def at(self, idx):
		if len(idx) == 0:
			return self
		elif idx[0] < len(self.members):
			return self.members[idx[0]].at(idx[1:])
		else:
			return None

class ChpArg:
	def __init__(self, name, vdir, clk="", posedge=True, ack=False):
		self.name = name
		self.vdir = vdir
		self.clk = clk
		self.posedge = posedge
		self.ack = ack

	def index(self, i):
		return ChpArg(self.name + "." + str(i), self.vdir, self.clk, self.posedge, self.ack)

def parseChpArgs(line):
	result = []
	for arg in line.split(","):
		arg = arg.strip()
		vdir = ""
		ack = False
		clk = ""
		posedge = True
		if '@' in arg:
			lst = arg.split("@")
			arg = lst[0]
			clk = lst[1]
			if len(clk) > 0 and clk[-1] in "+-":
				if clk[-1] == "-":
					posedge = False
				clk = clk[0:-1]

		if len(arg) > 0 and arg[-1] in "?!":
			vdir = arg[-1]
			arg = arg[0:-1]
		elif len(arg) > 1 and arg[-2] in "?!" and arg[-1] in "+-":
			vdir = arg[-2]
			ack = arg[-1] == "+"
			arg = arg[0:-2]
		
		result.append(ChpArg(arg, vdir, clk, posedge, ack))
	return result

class ChpTest:
	def __init__(self, proc, chptest):
		self.proc = proc
		self.chptest = chptest

	def testPath(self):
		name = shlex.quote(self.proc.test())
		if name[0] == '\'' and name[-1] == '\'':
			name = name[1:-1]
		return os.getcwd() + "/test/" + name

	def createDir(self):
		path = self.testPath()

		chp = ""
		for item in self.chptest[1:len(self.chptest)]:
			if chp != "":
				chp += " "
			chp += shlex.quote(item)

		cmd = 'go test ' + projectRoot() + '/... -v -run ' + shlex.quote("^"+self.chptest[0]+"$") + ' -args'
		if "ACT_PROFILE" in os.environ:
			cmd += ' \"' + projectRoot() + '/$ACT_PROFILE\"'
		else:
			cmd += ' \"\" '
		cmd += ' \'' + path + '/chp\' ' + chp

		os.system('mkdir -p \'' + path + '\'')
		print(cmd)
		os.system(cmd)
		
		return path

def parseChpTest():
	tests = []
	for line in os.popen("find * -name '*.act' | xargs grep -rh \"^//.*TestUnit\""):
		m = re.match(r'//\s*([^<]*)<([^>]*)>\(([^\)]*)\):(.*)', line)
		# TODO(edward.bingham) add support for multiple data streams for a single channel
		tests.append(ChpTest(ActInstance(m.group(1), parseArgs(m.group(2)), parseChpArgs(m.group(3))), m.group(4).strip().split(" ")))
	return tests

# Test Generator
###############################################################################

def prsimEmitChan(name, proto, req, ack, chp, vdir):
	return [
		"channel dut.{name} {proto} dut.{req}".format(
			name  = name,
			proto = proto,
			req = req) + (" dut.{ack}".format(ack=ack) if ack else ""),
		"{kind} dut.{name} request {chp}.dat".format(
			kind = "inject" if vdir == '?' else "expect",
			name = name,
			chp  = chp)
	]

def prsimEmitBus(name, clk, wires, posedge, pair, chp, vdir):
	if int(wires) > 0:
		return [
			"clocked_bus dut.{name}.d[0:{wires}] dut.{clk} {edge}{pair}{half}".format(
				name  = name,
				clk   = clk,
				wires = wires,
				edge  = "posedge" if posedge else "negedge",
				pair  = " pair" if pair else "",
				half = " half"),
			"{kind} dut.{name}.d[0:{wires}]{init} {chp}.dat".format(
				kind  = "inject" if vdir == '?' else "expect",
				name  = name,
				wires = wires,
				chp   = chp,
				init = " init" if vdir == '?' else "")
		]
	else:
		return [
			"clocked_bus dut.{name} dut.{clk} {edge}{pair}{half}".format(
				name  = name,
				clk   = clk,
				wires = wires,
				edge  = "posedge" if posedge else "negedge",
				pair  = " pair" if pair else "",
				half = " half"),
			"{kind} dut.{name}{init} {chp}.dat".format(
				kind  = "inject" if vdir == '?' else "expect",
				name  = name,
				wires = wires,
				chp   = chp,
				init = " init" if vdir == '?' else "")
		]

def openFileStruct(path, chp, name=""):
	if len(chp.name) > 0:
		if len(name) > 0:
			name += "."
		name += chp.name

	if len(chp.members) > 0:
		result = []
		for member in chp.members:
			result.append(openFileStruct(path, member, name))
		return result

	if len(name) > 0:	
		return open("{path}/{name}.dat".format(path=path,name=name), "w")

	return None

def closeFileStruct(files):
	for file in files:
		if isinstance(file, list):
			closeFileStruct(file)
		else:
			file.close()

def writeFileStruct(files, values):
	if len(values.members) > 0:
		for file, value in zip(files, values.members):
			writeFileStruct(file, value)
		return
	
	value = str(values)
	if value == "false":
		value = 0
	elif value == "true":
		value = 1
	print(value, file=files)


# str, ActArg, ChpArg
def createInjectExpect(path, act, chp):
	if len(act.size) > 0:
		for i in range(0, int(act.size[0])):
			createInjectExpect(path, act.index(i), chp.index(i))
		return
	
	elif chp.name and chp.vdir:
		chanpath = "{path}/chp/top.dut.{name}.{recv}".format(
			path=path,
			name=chp.name,
			recv=("r" if chp.vdir == '?' else "s"),
		)
		rec = None
		files = None
		with open(chanpath, "r") as chanptr:
			for i, line in enumerate(chanptr):
				if i == 0:
					# read the header
					rec = ChpStruct(line[10:])
					rec.name = chp.name
					files = openFileStruct(path, rec)
				else:
					inst = ChpStruct(line.split("\t")[1])
					writeFileStruct(files, inst)

def emitTestAct(path, test, proc):
	with open(path + "/test.act", "w") as fptr:
		print("import \"globals.act\";", file=fptr)
		print("import \"" + proc.path + "\";", file=fptr)
		print("import \"qdi/sink.act\";", file=fptr)
		print("", file=fptr)

		print("defproc testbench(" + proc.argdef() + ")", file=fptr)
		print("{", file=fptr)
		print("\t[ DUT ->", file=fptr)
		print("\t" + test.proc.typestr() + " dut;", file=fptr)
		for arg in proc.args:
			print("\t" + arg.name.split('[')[0] + " = dut." + arg.name.split('[')[0] + ";", file=fptr)
		print("\t]", file=fptr)
		print("}\n", file=fptr)

		for arg, val in zip(proc.args, test.proc.args):
			print(arg.inst() + ";", file=fptr)
			if val.name and val.vdir == '!' and not val.clk:
				print(arg.sink(), file=fptr)
			elif not val.name and not val.vdir and val.clk:
				print("{} = {};".format(arg.name, val.clk), file=fptr)

		print("testbench dut(" + proc.arglist() + ");", file=fptr)

def emitPrsimRc(path, name, test, proc, xyce = False):
	with open(path + "/" + name, "w") as fptr:
		print("initialize", file=fptr)
		if xyce:
			print("random 0 10", file=fptr)
		else:
			print("random", file=fptr)
		print("""random_excl on

set_reset g.Reset
""", file=fptr)

		channels = []
		for arg in proc.args:
			channels += arg.emitBundle()

		for arg, val in zip(proc.args, test.proc.args):
			if val.name:
				channels += arg.emit(val)

		print("\n".join(channels), file=fptr)

		print("""
watchall
mode reset
set g.Vdd 1
set g.GND 0
set g._sReset 0
set g.sReset 1
set g._pReset 1
set g.pReset 0""", file=fptr)

		if xyce:
			print("advance 400", file=fptr)
		else:
			print("cycle", file=fptr)

		print("""
set g._pReset 0
set g.pReset 1""", file=fptr)

		if xyce:
			print("advance 400", file=fptr)
		else:
			print("cycle", file=fptr)

		print("""
mode run
status X

set g._pReset 1
set g.pReset 0
set g._sReset 1
set g.sReset 0""", file=fptr)
		
		if xyce:
			print("advance 10000000", file=fptr)
		else:
			print("cycle", file=fptr)


def emitTest():
	root = projectRoot()
	if root == "/":
		print("pr test: go.mod file not found in current directory or any parent directory")

	processes = parseActProcess()
	tests = parseChpTest()
	
	for test in tests:
		name = test.proc.name
		if ':' in name:
			idx = name.rindex(':')
			name = name[idx+1:]

		if name in processes:
			proc = processes[name].flatten(test.proc.tmpl)
			path = test.createDir()
			relCwd = relativeCwd(root)
			if relCwd != ".":
				proc.path = relCwd + "/" + proc.path
			if proc.path.startswith("prs/"):
				proc.path = proc.path[4:]

			for arg, val in zip(proc.args, test.proc.args):
				createInjectExpect(path, arg, val)

			emitTestAct(path, test, proc)

			emitPrsimRc(path, "prsim.rc", test, proc, False)
			emitPrsimRc(path, "xyce.rc", test, proc, True)

def runSim(prs, prsim):
	sim = subprocess.Popen(["prsim", prs], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
	sim.stdin.write("source {}\n".format(prsim))
	sim.stdin.write("quit\n")
	out, err = sim.communicate()
	if err:
		print(err)
	sim.stdin.close()

	with open("test.sim", "w") as fptr:
		print(out, file=fptr)
	return out

# main
###############################################################################
if __name__ == "__main__":
	tech = "sky130"
	if len(sys.argv) > 1:
		if sys.argv[1] == "init" and len(sys.argv) > 2:
			os.system("git init")
			os.system("go mod init " + shlex.quote(sys.argv[2]))
			os.system("mkdir -p prs chp")
		elif sys.argv[1] == "vendor":
			os.system("vend")
		elif sys.argv[1] == "test":
			emitTest()
		elif sys.argv[1] == "sim":
			runSim("test.prs", "prsim.rc")
			buildChan("test.sim")
		elif sys.argv[1] == "view":
			if sys.argv[2].endswith(".sim"):
				target = buildVCD(sys.argv[2])
				os.system("gtkwave " + shlex.quote(target))
			elif sys.argv[2].endswith(".vcd"):
				os.system("gtkwave " + shlex.quote(sys.argv[2]))
			elif sys.argv[2].endswith(".prn"):
				os.system("gaw " + shlex.quote(sys.argv[2]))
		elif sys.argv[1] == "build" and os.path.exists("test.act") and os.path.exists("prsim.rc"):
			tech = "sky130"
			if len(sys.argv) > 2:
				tech = shlex.quote(sys.argv[2])
			os.system("ACT_PATH=\"" + projectRoot() + "/prs:$ACT_PATH\" aflat -T"+tech+" -DDUT=true -DPRSIM=true test.act > test.prs")
		elif sys.argv[1] == "spice" and os.path.exists("test.act") and os.path.exists("prsim.rc"):
			tech = "sky130"
			if len(sys.argv) > 2:
				tech = shlex.quote(sys.argv[2])
			if os.path.exists("spice"):
				os.system("rm -rf spice")
			os.system("ACT_PATH=\"" + projectRoot() + "/prs:$ACT_PATH\" prspice -C " + tech + " -p 'testbench<>' -i 'dut' -s 'g.Vdd=1.8v;g.GND=0.0v;gwrap.Vdd=1.8v;gwrap.GND=0.0v' test.act xyce.rc -o spice")
			os.system("mv spice/dut.spi spice/long.spi")
			shortenSpice("spice/long.spi", "spice/dut.spi")
			os.system("cp *.dat spice")

